services:
  express-api: #image名
    container_name: express-api-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./simpleAPI:/usr/src/app # ローカルをコンテナ内にマウント
    ports:
      - "3000:3000"
    stdin_open: true
    
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false